### PR TITLE
trademark™ unicode in game title throws error

### LINKED ISSUE #3: trademark™ unicode in game title throws error
While idling games with ™ (Unicode character 2122) in game title, I get this error:

```
Traceback (most recent call last):
  File "steam_idle_cli.py", line 158, in <module>
    main_idle(apps)
  File "steam_idle_cli.py", line 30, in main_idle
    p = IdleChild(app)
  File "/home/nick/.steam_idle/steam_idle/idle.py", line 18, in __init__
    self.name += '-[%s]' % str(self.app.name if self.app.name else self.app.appid)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2122' in position 24: ordinal not in range(128)
```

### PR DESCRIPTION
**Pull request by ghost**
While idling games with ™ (Unicode character 2122) in game title, I get this error:

```
Traceback (most recent call last):
  File "steam_idle_cli.py", line 158, in <module>
    main_idle(apps)
  File "steam_idle_cli.py", line 30, in main_idle
    p = IdleChild(app)
  File "/home/nick/.steam_idle/steam_idle/idle.py", line 18, in __init__
    self.name += '-[%s]' % str(self.app.name if self.app.name else self.app.appid)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2122' in position 24: ordinal not in range(128)
```

### CODE REVIEW

**Comment by jayme-github** [comment]
Thanks for the report and PR.
Could you try if the following works out for you too (would allow us to keep non ascii characters):

``` patch
diff --git a/steam_idle/idle.py b/steam_idle/idle.py
index 36e6849..700646e 100644
--- a/steam_idle/idle.py
+++ b/steam_idle/idle.py
@@ -15,7 +15,7 @@ class IdleChild(multiprocessing.Process):
     def __init__(self, app):
         super(IdleChild, self).__init__()
         self.app = app
-        self.name += '-[%s]' % str(self.app.name if self.app.name else self.app.appid)
+        self.name += '-[%s]' % self.app.name if self.app.name else str(self.app.appid)

     def run(self):
         os.environ['SteamAppId'] = str(self.app.appid)
```

I've tested this with AppID _233290_ using `mockSome` function (and the --verbose switch). If that works for you too, you could edit your PR and I will be happy to merge it! :+1:

**Comment by ghost** [comment]
Yes that works as well. I wasn't sure if you wanted to include non-ascii characters since I thought these are going to be printed to console, and I'm not sure about utf-8 support in Windows consoles.

Shall I commit this line into my PR? Or will you commit to master.

**Comment by jayme-github** [comment]
> I'm not sure about utf-8 support in Windows consoles.

Neither am I but let's try. :smiley:

**Comment by ghost** [comment]
Hmm, native UTF-8 support in Windows is not good, but default terminals bundled with Cygwin have good support. I say force the standard. I'll test, and update my PR.

**Comment by ghost** [comment]
Ok this is ready for a merge. I tested and worked nicely in my term.

Unless you'd like me to rebase back to ebe01604ec5c3d7792fdef8d31c860a7d508446b so as to remove 1d203b799c8c710b6576da2b05b828a125d8e151 from the history. (i guess i should probably do that. :stuck_out_tongue_closed_eyes: )

Thanks again for this super useful tool :smiley: :+1:

**Comment by jayme-github** [comment]
Let's ignore the git-foo, no need to waste time with that imho.

Windows, of cause, fails badly with unicode in Powershell and cmd but this seems to be a general python problem (http://bugs.python.org/issue1602). Could be worked around with https://github.com/Drekin/win-unicode-console as it seems but as this is more an environmental thing (and Windows guys could use the Qt Version) I will not fix this (at least for now :smile:).

Windows traceback for the record:

``` pytb
Traceback (most recent call last):
  File "E:\steam_idle\steam_idle_cli.py", line 155, in <module>
    print('"%s" has %d remaining drops, play time till now: %0.1f hours' % (app.
name, app.remainingDrops, app.playTime))
  File "C:\Python34\lib\encodings\cp850.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2122' in position 
23: character maps to <undefined>
```

**Comment by ghost** [comment]
And of course if you're on windows you can just use the original idle master :wink:

**Comment by jayme-github** [comment]
:fu: :smirk:

**Comment by ghost** [comment]
:grinning:

**Pull request merged**
